---
- name: show vars
  debug:
    msg: "trackstack_dir: {{ trackstack_dir }}"



- name: Create track stack environment directory
  ansible.builtin.file:
    state: directory
    path: "{{ trackstack_dir }}"
    owner: "{{ trackstack_dir_owner }}"
    group: "{{ trackstack_dir_group }}"
    mode: 0700


- name: Create stack storage subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ trackstack_dir }}/{{ item }}"
    mode: 0770
  loop:
    - data
    - config

- name: Create stack config subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ trackstack_dir }}/{{ item }}"
    mode: 0770
  loop:
    - config
    - config/traefik2
    - config/traefik2/rules
    - config/traefik2/acme
    - secrets


- name: Add DNS challenge secret
  ansible.builtin.copy:
#    todo: use ansible vault
    content: "{{ dns_challenge_api_token }}"
    dest: "{{ trackstack_dir }}/secrets/cloudflare_api_token"
    owner: root
    group: root
    mode: 0600

- name: copy traefik files to remote
  copy:
    src: "{{ role_path }}/files/traefik2/"
    dest: "{{ trackstack_dir }}/config/traefik2/"
    owner: "{{ trackstack_dir_owner }}"
    group: "{{ trackstack_dir_group }}"
    mode: 0600


- name: Create empty acme.json
  ansible.builtin.copy:
    content: ""
    dest: "{{ trackstack_dir }}/config/traefik2/acme/acme.json"
    owner: root
    group: root
    mode: 0600


- name: create traefik.log
  ansible.builtin.copy:
    content: ""
    dest: "{{ trackstack_dir }}/config/traefik2/traefik.log"
    owner: "{{ trackstack_dir_owner }}"
    group: "{{ trackstack_dir_group }}"
    mode: 0644

- name: create docker compose .env
  ansible.builtin.template:
    src: env_file.j2
    dest: "{{ trackstack_dir }}/.env"
    owner: "{{ trackstack_dir_owner }}"
    group: "{{ trackstack_dir_group }}"
    mode: 0600

- name: create .socketproxy.env
  ansible.builtin.template:
    src: .socketproxy.env
    dest: "{{ trackstack_dir }}/.socketproxy.env"
    owner: "{{ trackstack_dir_owner }}"
    group: "{{ trackstack_dir_group }}"
    mode: 0600

- name: create compose.yml file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ trackstack_dir }}/compose.yml"
    owner: "{{ trackstack_dir_owner }}"
    group: "{{ trackstack_dir_group }}"
    mode: 0600


- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ trackstack_dir }}"
    pull: missing
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
