http:
  middlewares:

    ################ MIDDLEWARES

    # middlewares-basic-auth:
    #   basicAuth:
    #     # users:
    #     #   - "user:$apsdfswWvC/6.$E3FtsfTntPC0wVJ7IUVtX1"
    #     usersFile: "/run/secrets/htpasswd" #be sure to mount the volume through docker-compose.yml
    #     realm: "Traefik 2 Basic Auth"

    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    middlewares-https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: SAMEORIGIN # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex," # disable search engines from indexing home server
          server: "" # hide server info from visitors

    middlewares-compress:
      compress: { }

    # https://stackoverflow.com/questions/49717670/how-to-config-upload-body-size-restriction-in-traefik
    middlewares-buffering:
      buffering:
        maxResponseBodyBytes: 2000000
        maxRequestBodyBytes: 10485760
        memRequestBodyBytes: 2097152
        memResponseBodyBytes: 2097152
        retryExpression: "IsNetworkError() && Attempts() <= 2"


    ################ CHAINS
    chain-no-auth:
      chain:
        middlewares:
          #- middlewares-traefik-bouncer # leave this out if you are not using CrowdSec
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-compress

    chain-no-rate-limit-no-auth:
      chain:
        middlewares:
          #- middlewares-traefik-bouncer # leave this out if you are not using CrowdSec
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-compress


